name: glaes
channels:
  - conda-forge
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - pip
  - matplotlib
  - descartes
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - gdal>=3,<4
  - pip:
      - git+https://github.com/coroa/geokit.git@v1.4.0#egg=geokit
      - .
